name: tests

on: [push, pull_request]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up the PHP version you support
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'    # or 8.2 / 8.1
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run test suite
        run: composer test
